allowBuilds:
  sharp: true
  unrs-resolver: true
overrides:
  brace-expansion@1: ^1.1.13
  brace-expansion@2: ^2.0.2
  flatted: ^3.4.2
  js-yaml: ^3.14.2
  mdast-util-to-hast: ^13.2.1
  minimatch@1: ^1.1.4
  minimatch@3: ^3.1.4
  picomatch@2: ^2.3.2
  picomatch@4: ^4.0.4
  postcss: ^8.5.15
  yaml@1: ^1.10.2
  yaml@2: ^2.8.3
